### ISSUE TITLE
platform ve website kurulum dosyaları

### ISSUE THREAD

**Issue by volkangurol** [imonacom/imonagame#1]
[ImonaGame-Website-Deployment.docx](https://github.com/imonacom/imonagame/files/2188501/ImonaGame-Website-Deployment.docx)
[ImonaCloud-Platform-Deployment.docx](https://github.com/imonacom/imonagame/files/2188502/ImonaCloud-Platform-Deployment.docx)

**Comment by imonacom** [comment]
![image](https://user-images.githubusercontent.com/1706751/42632774-fea46460-85e6-11e8-9483-35ad43d6dcf2.png)
